// sui.js — Sui client helpers + in-process email decryption
//
// Decryption is done inline using the Web Crypto API (available natively in
// Cloudflare Workers) — no separate decrypt worker or internal fetch needed.
// The private key lives in the PRIVATE_KEY env var as a base64-encoded PKCS#8
// blob — exactly what the key generation script exports via
// subtle.exportKey('pkcs8', keyPair.privateKey).
//
// Client strategy (based on @mysten/sui@2.x package structure):
//
//   SuiGrpcClient    (@mysten/sui/grpc)    — object fetching, dynamic fields
//   SuiJsonRpcClient (@mysten/sui/jsonRpc) — event querying (queryEvents),
//                                            getDynamicFieldObject

import { SuiGrpcClient, GrpcWebFetchTransport } from '@mysten/sui/grpc'
import { SuiJsonRpcClient, getJsonRpcFullnodeUrl } from '@mysten/sui/jsonRpc'

// ── Client factory ────────────────────────────────────────────────────────────

/**
 * Create both Sui clients from the worker environment.
 *
 * Env vars (all optional — defaults to testnet):
 *   SUI_NETWORK  — 'mainnet' | 'testnet' | 'devnet' | 'localnet'
 *   SUI_GRPC_URL — gRPC-web base URL, e.g. https://sui-mainnet.mystenlabs.com
 *   SUI_RPC_URL  — JSON-RPC endpoint (for queryEvents)
 *
 * Returns { grpc, rpc }
 */
export function makeClients(env) {
  const network = env.SUI_NETWORK || 'testnet'

  const grpc = new SuiGrpcClient(
    env.SUI_GRPC_URL
      ? { network, transport: new GrpcWebFetchTransport({ baseUrl: env.SUI_GRPC_URL }) }
      : { network }
  )

  const rpc = new SuiJsonRpcClient({
    url: env.SUI_RPC_URL || getJsonRpcFullnodeUrl(network),
  })

  return { grpc, rpc }
}

// ── Hashing ───────────────────────────────────────────────────────────────────

/**
 * sha256(str) → lowercase hex string.
 */
export async function sha256hex(str) {
  const data = new TextEncoder().encode(str)
  const buf  = await crypto.subtle.digest('SHA-256', data)
  return Array.from(new Uint8Array(buf))
    .map(b => b.toString(16).padStart(2, '0'))
    .join('')
}

/**
 * Normalise and hash a sender email address.
 * sha256( email.toLowerCase().trim() )
 * Must match the frontend hashing exactly.
 */
export async function hashEmail(email) {
  return sha256hex(email.toLowerCase().trim())
}

/**
 * Compute the payment_id for a sender/vault pair.
 * sha256( emailHash + ':' + vaultId )
 * Must match Profile.jsx and the Move contract exactly.
 */
export async function computePaymentId(email, vaultId) {
  const emailHash = await hashEmail(email)
  return sha256hex(`${emailHash}:${vaultId}`)
}

// ── Registry lookup ───────────────────────────────────────────────────────────

/**
 * Resolve a full gateway email (e.g. "alice@attention.email") to a vault ID
 * by querying the Registry's gateway_emails Table<String, ID> dynamic field.
 * Returns the vault ID string (0x-prefixed), or null if not found.
 */
export async function vaultIdByGatewayEmail(grpc, registryId, gatewayEmail) {
  if (!registryId) return null
  try {
    const result = await grpc.getDynamicField({
      parentId: registryId,
      name: {
        type: '0x1::string::String',
        bcs:  stringToBcs(gatewayEmail),
      },
    })
    const valueBcs = result?.dynamicField?.value?.bcs
    if (!valueBcs || valueBcs.length === 0) return null
    return '0x' + bytesToHex(valueBcs)
  } catch (err) {
    console.error('[sui] vaultIdByGatewayEmail error:', err.message)
    return null
  }
}

// ── Vault object ──────────────────────────────────────────────────────────────

/**
 * Fetch vault content fields via JSON-RPC (returns parsed field map).
 * Used when structured field access is needed (encrypted email blobs, tables).
 * Returns the fields object or null.
 */
export async function fetchVaultFieldsRpc(rpc, vaultId) {
  try {
    const obj = await rpc.getObject({
      id:      vaultId,
      options: { showContent: true },
    })
    return obj?.data?.content?.fields ?? null
  } catch (err) {
    console.error('[sui] fetchVaultFieldsRpc error:', err.message)
    return null
  }
}

/**
 * Pull the three encrypted-email blobs from a vault fields object.
 * Returns them as Base64 strings ready for decryptSellerEmail().
 *
 * Move fields (all vector<u8>):
 *   encrypted_email_ephemeral_pubkey
 *   encrypted_email_iv
 *   encrypted_email_ciphertext
 *
 * JSON-RPC returns vector<u8> as number arrays; hex strings are also handled.
 */
export function extractEncryptedEmailPayload(vaultFields) {
  return {
    ephemeralPublicKey: bytesToBase64(vaultFields.encrypted_email_ephemeral_pubkey),
    iv:                 bytesToBase64(vaultFields.encrypted_email_iv),
    ciphertext:         bytesToBase64(vaultFields.encrypted_email_ciphertext),
  }
}

// ── In-process ECDH + AES-GCM decryption ─────────────────────────────────────
//
// Matches the scheme in encrypt.js (frontend):
//   1. Ephemeral P-256 key pair generated by sender.
//   2. ECDH shared secret derived with recipient's static P-256 public key.
//   3. Shared secret used as AES-256-GCM key to encrypt the email.
//   4. ephemeralPublicKey + iv + ciphertext stored on-chain (all Base64).
//
// To decrypt we reverse steps 2-3 using the recipient's static private key,
// which is stored in the PRIVATE_KEY env var as a base64-encoded PKCS#8 blob —
// exactly what `subtle.exportKey('pkcs8', keyPair.privateKey)` produces from
// the key generation script. We import it directly with no transformation.

/**
 * Import the gateway's static P-256 private key from the PRIVATE_KEY env var.
 * The env var holds a base64-encoded PKCS#8 export of the private key,
 * as produced by: subtle.exportKey('pkcs8', keyPair.privateKey)
 *
 * @param {string} privateKeyBase64
 * @returns {Promise<CryptoKey>}
 */
async function importPrivateKey(privateKeyBase64) {
  return crypto.subtle.importKey(
    'pkcs8',
    base64ToBytes(privateKeyBase64),
    { name: 'ECDH', namedCurve: 'P-256' },
    false,
    ['deriveKey']
  )
}

/**
 * Decrypt the seller's real email address from the on-chain encrypted payload.
 *
 * Env var required:
 *   PRIVATE_KEY — base64-encoded PKCS#8 export of the P-256 private key
 *
 * @param {object} env
 * @param {{ ephemeralPublicKey: string, iv: string, ciphertext: string }} payload
 *   All values are Base64 strings, as produced by extractEncryptedEmailPayload().
 * @returns {Promise<string|null>} plaintext email address, or null on failure
 */
export async function decryptSellerEmail(env, payload) {
  if (!env.PRIVATE_KEY) {
    console.error('[decrypt] PRIVATE_KEY env var not set')
    return null
  }
  try {
    const { ephemeralPublicKey, iv, ciphertext } = payload

    // 1. Import the gateway static private key
    const privateKey = await importPrivateKey(env.PRIVATE_KEY)

    // 2. Import the ephemeral public key that was stored on-chain
    const ephemeralPubKey = await crypto.subtle.importKey(
      'raw',
      base64ToBytes(ephemeralPublicKey),
      { name: 'ECDH', namedCurve: 'P-256' },
      false,
      []
    )

    // 3. Re-derive the AES-256-GCM key via ECDH (same shared secret as encryption)
    const aesKey = await crypto.subtle.deriveKey(
      { name: 'ECDH', public: ephemeralPubKey },
      privateKey,
      { name: 'AES-GCM', length: 256 },
      false,
      ['decrypt']
    )

    // 4. Decrypt
    const plaintext = await crypto.subtle.decrypt(
      { name: 'AES-GCM', iv: base64ToBytes(iv) },
      aesKey,
      base64ToBytes(ciphertext)
    )

    return new TextDecoder().decode(plaintext)
  } catch (err) {
    console.error('[decrypt] Decryption failed:', err.message ?? err)
    return null
  }
}

// ── Dynamic field helpers ─────────────────────────────────────────────────────

/**
 * Check whether a vector<u8> key exists in a Move Table dynamic field.
 * Returns true if the entry is present.
 */
async function tableHasKey(rpc, tableId, hexKey) {
  if (!tableId) return false
  const keyBytes = hexToNumberArray(hexKey)
  try {
    const result = await rpc.getDynamicFieldObject({
      parentId: tableId,
      name:     { type: 'vector<u8>', value: keyBytes },
    })
    return !!result?.data
  } catch {
    return false
  }
}

/**
 * Check whether a conversation thread is closed on-chain.
 * vault.closed_threads[payment_id] present → closed.
 */
export async function isThreadClosed(rpc, vaultFields, paymentIdHex) {
  const tableId = vaultFields?.closed_threads?.fields?.id?.id
  return tableHasKey(rpc, tableId, paymentIdHex)
}

// ── SlotWon event index ───────────────────────────────────────────────────────

/**
 * Fetch all SlotWon events for a vault and return a lookup map:
 *   paymentId (hex) → { senderEmailHash: string, bidderAddress: string }
 *
 * Later events overwrite earlier ones — last winning bid for a paymentId wins.
 * Uses the JSON-RPC client (the only client surface with queryEvents).
 */
export async function fetchSlotWonMap(rpc, packageId, vaultId) {
  const map = {}
  try {
    let cursor = null
    while (true) {
      const result = await rpc.queryEvents({
        query:  { MoveEventType: `${packageId}::attention_market::SlotWon` },
        cursor,
        limit:  50,
        order:  'ascending',
      })
      for (const event of result.data) {
        const p = event.parsedJson
        if (p.vault_id !== vaultId) continue
        map[bytesToHex(p.payment_id)] = {
          senderEmailHash: bytesToHex(p.sender_email_hash),
          bidderAddress:   p.bidder,
        }
      }
      if (!result.hasNextPage) break
      cursor = result.nextCursor
    }
  } catch (err) {
    console.error('[sui] fetchSlotWonMap error:', err.message)
  }
  return map
}

// ── Utilities ─────────────────────────────────────────────────────────────────

/** Base64 string → Uint8Array */
function base64ToBytes(b64) {
  const binary = atob(b64)
  const bytes  = new Uint8Array(binary.length)
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i)
  return bytes
}

/** Hex string → number array (for Move vector<u8> dynamic field keys) */
export function hexToNumberArray(hex) {
  const bytes = []
  for (let i = 0; i < hex.length; i += 2)
    bytes.push(parseInt(hex.slice(i, i + 2), 16))
  return bytes
}

/** Byte array or hex string → lowercase hex string */
export function bytesToHex(bytes) {
  if (typeof bytes === 'string') return bytes
  return Array.from(bytes)
    .map(b => b.toString(16).padStart(2, '0'))
    .join('')
}

/**
 * Encode a JS string as BCS bytes for 0x1::string::String.
 * BCS String = ULEB128 length prefix + UTF-8 bytes.
 */
function stringToBcs(str) {
  const utf8      = new TextEncoder().encode(str)
  const lenBytes  = []
  let   remaining = utf8.length
  do {
    let byte = remaining & 0x7f
    remaining >>= 7
    if (remaining > 0) byte |= 0x80
    lenBytes.push(byte)
  } while (remaining > 0)
  const result = new Uint8Array(lenBytes.length + utf8.length)
  result.set(lenBytes)
  result.set(utf8, lenBytes.length)
  return result
}

/**
 * Convert a Sui vector<u8> field value to a Base64 string.
 * JSON-RPC returns these as number arrays; hex strings are also handled.
 */
function bytesToBase64(value) {
  if (!value) return ''
  const bytes = typeof value === 'string' ? hexToNumberArray(value) : Array.from(value)
  return btoa(String.fromCharCode(...bytes))
}